=== kraw/maddaaiMagento/code/EasyNolo/BancaSellaPro/etc/alternative_payments.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="1" maxOccurs="unbounded" name="alternative_payments" type="alternativePayments" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="alternativePayments">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="unbounded" name="payment" type="payment" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="payment">
        <xs:sequence>
            <xs:element minOccurs="1" maxOccurs="1" name="code" />
            <xs:element minOccurs="1" maxOccurs="1" name="title" />
            <xs:element minOccurs="1" maxOccurs="1" name="type" />
            <xs:element minOccurs="0" maxOccurs="1" name="template" />
            <xs:element minOccurs="0" maxOccurs="1" name="encrypt_helper" />
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== kraw/maddaaiMagento/code/EasyNolo/BancaSellaPro/etc/alternative_payments.xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="alternative_payments.xsd">
    <alternative_payments>
        <payment>
            <code>alipay</code>
            <title>Alipay</title>
            <type>S2PALI</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>alipay</code>
            <title>Alipay</title>
            <type>S2PALI</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>bitcoin</code>
            <title>Bitcoin</title>
            <type>S2PBIT</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>consel</code>
            <title>Consel</title>
            <type>CONSEL</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>eps</code>
            <title>EPS</title>
            <type>S2PALI</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>giropay</code>
            <title>Giropay</title>
            <type>S2PGIR</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>mybank</code>
            <title>MyBank</title>
            <type>MYBANK</type>
            <template>default.phtml</template>
            <encrypt_helper>EasyNolo\BancaSellaPro\Helper\AlternativePayments\Mybank</encrypt_helper>
        </payment>
        <payment>
            <code>ideal</code>
            <title>IDeal</title>
            <type>IDEAL</type>
            <template>default.phtml</template>
            <encrypt_helper>EasyNolo\BancaSellaPro\Helper\AlternativePayments\Ideal</encrypt_helper>
        </payment>
        <payment>
            <code>klarna</code>
            <title>Klarna</title>
            <type>S2PKLA</type>
            <template>klarna.phtml</template>
            <encrypt_helper>EasyNolo\BancaSellaPro\Helper\AlternativePayments\Klarna</encrypt_helper>
        </payment>
        <payment>
            <code>konbini</code>
            <title>Konbini</title>
            <type>S2PKON</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>mercadopago</code>
            <title>MercadoPago</title>
            <type>S2PMER</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>multibanco</code>
            <title>Multibanco</title>
            <type>S2PMUL</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>paypal</code>
            <title>Paypal</title>
            <type>PAYPAL</type>
            <template>default.phtml</template>
            <encrypt_helper>EasyNolo\BancaSellaPro\Helper\AlternativePayments\Paypal</encrypt_helper>
        </payment>
        <payment>
            <code>paysafecard</code>
            <title>Paysafecard</title>
            <type>S2PPSC</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>qiwi</code>
            <title>Qiwi</title>
            <type>S2PQIW</type>
            <template>default.phtml</template>
            <encrypt_helper>EasyNolo\BancaSellaPro\Helper\AlternativePayments\Qiwi</encrypt_helper>
        </payment>
        <payment>
            <code>sofort</code>
            <title>Sofort</title>
            <type>S2PSOF</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>tenpay</code>
            <title>TenPay</title>
            <type>S2PTEN</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>timpersonal</code>
            <title>TIMpersonal</title>
            <type>TIMPERSONAL</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>unionpay</code>
            <title>UnionPay</title>
            <type>S2PUNI</type>
            <template>default.phtml</template>
            <encrypt_helper>EasyNolo\BancaSellaPro\Helper\AlternativePayments\UnionPay</encrypt_helper>
        </payment>
        <payment>
            <code>webmoney</code>
            <title>WebMoney</title>
            <type>S2PWMO</type>
            <template>default.phtml</template>
        </payment>
        <payment>
            <code>yandex</code>
            <title>Yandex</title>
            <type>S2PYAN</type>
            <template>default.phtml</template>
        </payment>
    </alternative_payments>
</config>
